// ReadReviews.styles.ts
import { StyleSheet } from "react-native";

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: "#FFF",
  },
  divider: {
        width: "80%",
        height: 2,
        left:35,
        backgroundColor: "#000",
        marginBottom: 20,
    },
  backButton: {
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "400",
    color: "#000",
  },
  yummi: {
    fontWeight: "700",
    letterSpacing: 2,
  },
  scrollContent: {
    padding: 20,
  },
  productCard: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#A6B89F",
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
  },
  productImage: {
    width: 70,
    height: 70,
    borderRadius: 12,
    marginRight: 12,
    backgroundColor: "#F0F0F0",
  },
  productInfo: {
    flex: 1,
  },
  productName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000",
    marginBottom: 4,
  },
  productDescription: {
    fontSize: 13,
    color: "#666",
    lineHeight: 18,
  },
  visitButton: {
    position: "absolute",
    top: -15,
    right: -5,
    backgroundColor: "#778959",
    borderColor: "#ffffffff",
    borderWidth: 2,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  visitButtonText: {
    color: "#FFF",
    fontSize: 13,
    fontWeight: "600",
  },
  reviewBox: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#A6B89F",
    borderRadius: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  reviewerName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000",
    marginBottom: 12,
  },
  reviewText: {
    fontSize: 15,
    color: "#333",
    lineHeight: 22,
  },
    // Star row container
  starsRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
});